// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CheckMatrices():Promise<boolean>;

export function GetResults():Promise<service.Results>;

export function ListAdd(arg1:string):Promise<void>;

export function ListExport():Promise<service.ListFile>;

export function ListGet():Promise<Array<string>>;

export function ListRemove(arg1:number):Promise<void>;

export function LoadMatrix(arg1:string):Promise<string>;

export function LoadResult(arg1:string):Promise<string>;

export function SaveMatrix(arg1:string,arg2:Array<any>,arg3:string):Promise<void>;

export function SaveResult(arg1:string,arg2:Array<any>,arg3:string):Promise<void>;
