// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMatrices() {
  return window['go']['main']['App']['CheckMatrices']();
}

export function CheckResults(arg1) {
  return window['go']['main']['App']['CheckResults'](arg1);
}

export function CreateExcelFile(arg1) {
  return window['go']['main']['App']['CreateExcelFile'](arg1);
}

export function GetResults() {
  return window['go']['main']['App']['GetResults']();
}

export function ListAdd(arg1) {
  return window['go']['main']['App']['ListAdd'](arg1);
}

export function ListExport() {
  return window['go']['main']['App']['ListExport']();
}

export function ListGet() {
  return window['go']['main']['App']['ListGet']();
}

export function ListRemove(arg1) {
  return window['go']['main']['App']['ListRemove'](arg1);
}

export function LoadMatrix(arg1) {
  return window['go']['main']['App']['LoadMatrix'](arg1);
}

export function LoadResult(arg1) {
  return window['go']['main']['App']['LoadResult'](arg1);
}

export function SaveMatrix(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMatrix'](arg1, arg2, arg3);
}

export function SaveOriginalMatrix(arg1, arg2) {
  return window['go']['main']['App']['SaveOriginalMatrix'](arg1, arg2);
}

export function SaveResult(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveResult'](arg1, arg2, arg3);
}

export function SaveTestDate(arg1) {
  return window['go']['main']['App']['SaveTestDate'](arg1);
}

export function ShowSaveExcelDialog() {
  return window['go']['main']['App']['ShowSaveExcelDialog']();
}
